//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeManagement.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country field is required.
        /// </summary>
        public static string country_required {
            get {
                return ResourceManager.GetString("country_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department field is required.
        /// </summary>
        public static string department_required {
            get {
                return ResourceManager.GetString("department_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem while adding the data.
        /// </summary>
        public static string failed_addData {
            get {
                return ResourceManager.GetString("failed_addData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem while deleting the data.
        /// </summary>
        public static string failed_deleteData {
            get {
                return ResourceManager.GetString("failed_deleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem while getting the data.
        /// </summary>
        public static string failed_getData {
            get {
                return ResourceManager.GetString("failed_getData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem while updating the data.
        /// </summary>
        public static string failed_updateData {
            get {
                return ResourceManager.GetString("failed_updateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered id is out of the range.
        /// </summary>
        public static string Id_range {
            get {
                return ResourceManager.GetString("Id_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID field is required.
        /// </summary>
        public static string Id_required {
            get {
                return ResourceManager.GetString("Id_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of full name field is 100 digit.
        /// </summary>
        public static string name_length {
            get {
                return ResourceManager.GetString("name_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name field is required.
        /// </summary>
        public static string name_required {
            get {
                return ResourceManager.GetString("name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string phone_invalid {
            get {
                return ResourceManager.GetString("phone_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number field is required.
        /// </summary>
        public static string phone_required {
            get {
                return ResourceManager.GetString("phone_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered salary is out of the range.
        /// </summary>
        public static string salary_range {
            get {
                return ResourceManager.GetString("salary_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Field is required.
        /// </summary>
        public static string salary_required {
            get {
                return ResourceManager.GetString("salary_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
    }
}
